version: '2'
networks:
  project:
services:
  project:
    build:
      context: ../../
      dockerfile: ./Docker/dev/project/Dockerfile
    image: ai3/quarteznet
    volumes:
      - ../../app/:/home/docker/app/:rw
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    links:
      - postgresql:postgresql
    networks:
      project:
        aliases:
          - project
  postgresql:
    image: mdillon/postgis:11
    volumes:
      - ../../databases/dev/postgresql/data:/var/lib/postgresql/data:rw
    # ports:
    #   - "5430:5432"
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=Pr0JecT
    networks:
      project:
        aliases:
          - postgresql

